const input=document.getElementById('fileInput'),video=document.getElementById('video'),modal=document.getElementById('modal');let items=[],index=-1;const $=id=>document.getElementById(id);
function fmt(s){if(!isFinite(s))return'0:00';s=Math.floor(s);return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}
function openFiles(){input.click()}['addVideo','addVideoSide','heroAdd'].forEach(id=>$(id).onclick=openFiles);
input.onchange=e=>{[...e.target.files].forEach(file=>{if(!items.some(x=>x.name===file.name&&x.size===file.size)){items.push({file,name:file.name,size:file.size,fav:false,url:URL.createObjectURL(file)})}});render();input.value=''};
function render(){renderGrid($('recent'),items.slice(-8).reverse());renderGrid($('favoriteList'),items.filter(x=>x.fav));$('library').innerHTML=items.length?items.map((x,i)=>`<div class="video-row"><div class="row-thumb"><video src="${x.url}" preload="metadata"></video></div><div class="row-meta"><strong>${esc(x.name)}</strong><span>${size(x.size)} • MP4/video</span></div><div class="row-actions"><button class="icon-btn" onclick="playAt(${i})">▶</button><button class="icon-btn" onclick="fav(${i})">${x.fav?'♥':'♡'}</button></div></div>`).join(''):`<div class="empty">🎬<strong>Your video library is empty</strong>Add MP4 files to start watching.</div>`}
function renderGrid(el,list){el.innerHTML=list.length?list.map(x=>{let i=items.indexOf(x);return`<article class="video-card" onclick="playAt(${i})"><div class="thumb"><video src="${x.url}" preload="metadata"></video><div class="play-overlay">▶</div></div><strong>${esc(x.name)}</strong><span>${size(x.size)} ${x.fav?'• ♥ Favorite':''}</span></article>`}).join(''):`<div class="empty">🎬<strong>No videos here yet</strong>Add a video to begin.</div>`}
function playAt(i){index=i;let x=items[i];video.src=x.url;video.load();$('nowTitle').textContent=x.name;$('nowMeta').textContent=size(x.size)+' • MP4';$('modalTitle').textContent=x.name;$('modalMeta').textContent=size(x.size)+' • Local video';modal.hidden=false;$('player').hidden=false;video.play().catch(()=>{});sync();mediaSession(x)}
function sync(){video.onloadedmetadata=()=>{$('duration').textContent=fmt(video.duration)};video.ontimeupdate=()=>{$('current').textContent=fmt(video.currentTime);$('progress').value=video.duration?video.currentTime/video.duration*100:0};video.onplay=()=>{$('play').textContent='Ⅱ';$('modalPlay').textContent='Ⅱ'};video.onpause=()=>{$('play').textContent='▶';$('modalPlay').textContent='▶'};video.onended=()=>next()}
$('play').onclick=()=>video.paused?video.play():video.pause();$('modalPlay').onclick=()=>video.paused?video.play():video.pause();$('progress').oninput=e=>{if(video.duration)video.currentTime=e.target.value/100*video.duration};$('volume').oninput=e=>video.volume=e.target.value;$('prev').onclick=()=>{if(video.currentTime>5)video.currentTime=0;else playAt((index-1+items.length)%items.length)};$('next').onclick=next;$('back10').onclick=()=>video.currentTime=Math.max(0,video.currentTime-10);$('forward10').onclick=()=>video.currentTime=Math.min(video.duration||0,video.currentTime+10);$('fullscreen').onclick=full;$('modalFull').onclick=full;function full(){if(video.requestFullscreen)video.requestFullscreen()};$('close').onclick=()=>{video.pause();modal.hidden=true};
function next(){if(items.length)playAt((index+1)%items.length)}function fav(i){items[i].fav=!items[i].fav;render()};window.playAt=playAt;window.fav=fav;
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(b.dataset.view).classList.add('active-view')});
$('search').oninput=e=>{let q=e.target.value.toLowerCase();renderGrid($('recent'),items.filter(x=>x.name.toLowerCase().includes(q)).slice(-8).reverse())};
function size(n){if(n<1048576)return Math.round(n/1024)+' KB';return(n/1048576).toFixed(1)+' MB'}function esc(s){return s.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]))}
function mediaSession(x){if(!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:x.name,artist:'Universal MP4 Player',album:'My Videos'});navigator.mediaSession.setActionHandler('play',()=>video.play());navigator.mediaSession.setActionHandler('pause',()=>video.pause());navigator.mediaSession.setActionHandler('seekbackward',()=>video.currentTime=Math.max(0,video.currentTime-10));navigator.mediaSession.setActionHandler('seekforward',()=>video.currentTime=Math.min(video.duration,video.currentTime+10));}catch(e){}}
render();sync();